### ISSUE TITLE
Mojolicious::Controller->url_for incorrectly decodes URI-special chars

### ISSUE THREAD

**Issue by dboehmer** [kraih/mojo#1023]
* Mojolicious version: 7.11
* Perl version: 5.20.2
* Operating system: Debian Linux Jessie (8)

### Test file

See gist https://gist.github.com/dboehmer/439d86e1102348c4d081b01b22f96c46.

### Steps to reproduce the behavior
Receive a 302 HTTP response with Location header with URI-special chars, e.g. `Location: /#foo=42&bar=%2520` (The key `bar` should have the decoded value `%20`). The code **behaves differently if the header value contains a `?` instead of a `#`**.

### Expected behavior
* `$t->tx->req->to_string` prints the request unmodified.
* `$t->tx->req->header('Location')` returns the header unmodified.

### Actual behavior
* encoded chars are decoded while unencoded chars stay as there are, leading to invalid results, e.g. `/#foo=42&bar=%20` for the input above.

### Why I am doing this

I am actually trying to redirect the HTTP client to another URL with data in an anchor that might contains arbitrary characters that need to be encoded.

My original problem was that in my test the location header was reported being different from the value set in the server. With the help of `#mojo` IRC channel I tracked down the problem to `url_for()`.

**Comment by jberger** [comment]
Ok so let me see if I understand correctly. You want to `redirect_to` to a different url within the same application, thus a relative url is used. You want some data in the fragment (anchor) section of the url.

From your example code I see that you are manually url encoding url that will become a "query parameter" in the fragment. I'm guessing you are doing some front-end-routing which tries to pretend that the fragment contains a query. I think you probably just need to encode/decode the fragment manually.

You can still use the functionality in Mojolicious to do so of course.

```
$ perl -Mojo -E 'say Mojo::URL->new("/")->fragment(Mojo::Parameters->new->pairs([foo => "bar", str => "foo://xyz?bar=baz+%20"]))'
/#foo=bar&str=foo%3A%2F%2Fxyz%3Fbar%3Dbaz%2B%2520
```

and to decode

```
$ perl -Mojo -E 'say Mojo::Parameters->new->parse(Mojo::URL->new("/#foo=bar&str=foo%3A%2F%2Fxyz%3Fbar%3Dbaz%2B%2520")->fragment)->param("str")'
foo://xyz?bar=baz  
```

Now the next problem is maybe that by using `redirect_to` (which internally calls `url_for`) you might be getting a second encoding pass. To avoid this you can do one of the following (untested, but at least one of these should work).
 
First, pass an instance of `Mojo::URL` rather than a string. As I've shown above you can construct a `Mojo::URL` that looks correct and `url_for` simply passes that through rather than trying to manipulate it. Or second, set the location header yourself and render a 302 yourself.

```perl
get '/redir' => sub {
  my $c = shift;
  $c->res->headers->location($target);
  $c->rendered(302);
};
```

I don't think there is much else the framework can do for you and I don't immediately see a bug (though indeed url handling is some of the hardest stuff in web work). I'm going to close this for now. If you feel there is a true bug involved please add more detail and reopen.

**Comment by ilainftw** [comment]
FWIW: Mojo::URL::parse (called by `url_for`) decodes and unescapes a URL fragment part but not a query string. However, the reverse process isn't completely symmetric. The way Mojo::URL::to_string calls Mojo::Util::url_escape to reconstruct the fragment means that your already-escaped input value isn't "double-escaped" on output as you are expecting it to be in your second test. I think you may need to use some manual intervention to get the location header you want.

**Comment by kraih** [comment]
Yes, you'd need a special container for the fragment, like the query currently has. Hardly seems worth the trouble.

**Comment by dboehmer** [comment]
As discussed in IRC this is actually a problem in `Mojo::URL`. This module handles de-/encoding of fragments and other parts like the query differently. The reason for this seems to be that the query is represented by an object with internal state while the fragment is only a string with no state saying whether it's already encoded.

I've got some new test cases which might illustrate what's the problem better than before:

- fragment is handled differently from query
```perl
say Mojo::URL->new("host?query=%25#fragment=%25");
# host?query=%25#fragment=%
```

- constructing Mojo::URL objects results in unequal URLs, even when providing an existing Mojo::URL object
  - using Mojo::URL as a container for an URL makes you actually loose data
```perl
say Mojo::URL->new(Mojo::URL->new("host?query=%252627#fragment=%252627"));
# host?query=%252627#fragment=&27
```

- passing a fragment part with obviously not encoded characters (`♥` is from an example in Mojo::URL's POD, `<` or `>` also apply) makes Mojo::URL encode *part of the* fragment while the `%` isn't
```perl
say Mojo::URL->new("host#fragment=♥%25");
# host#fragment=%E2%99%A5%
```

Please define the encoding type of the string argument to constructor and the `Mojo::URL->fragment()` method and the type of fragment string stored inside a `Mojo::URL` object and allow passing either a completely encoded string or passing a completely unencoded string which gets completely encoded.

I invested a whole bunch of my time to work through the [URL Living Standard](https://url.spec.whatwg.org/) but I wasn't able to identify if the document addresses this issue and what it says about it (if anything). If the design of `Mojo::URL` regarding this issue depends on this standard, please file a bug there.

**Comment by kraih** [comment]
Should we ever find a good reason to make changes in one of the specs, i think turning the `fragment` attribute into a method like this would work.
```
sub fragment {
  my $self = shift;

  return
    exists $self->{fragment} ? _decode(url_unescape $self->{fragment}) : undef
    unless @_;
  $self->{fragment} = shift;

  return $self;
}
```

**Comment by ilainftw** [comment]
This still doesn't make sense to me. dboehmer showed that an invalid URL could be produced from valid input:

    say Mojo::URL->new("/foo?bar=1%25+nacl#1%25+nacl")
    # /foo?bar=1%25+nacl#1%+nacl

which is invalid syntax according to RFC 3986, RFC 3987 and the URL Living Standard. Is there ever a case where a percent character can be represented in a URL by anything other than its percent-encoded value (`%25`)? The syntax rules in all 3 specs preclude it, but maybe there is more to the story. 

Beyond that, there is an inconsistency in how Mojo::URL handles fragments. You get a different, valid URL if you supply the same input to the fragment accessor, unlike when parsing a full URL: 

    say Mojo::URL->new("/foo")->query("1%25+nacl")->fragment("1%25+nacl")
    # /foo?1%25+nacl#1%25+nacl

As was pointed out in the earlier IRC discussion, this inconsistency arises because Mojo::URL->parse() unescapes a percent character in the fragment while Mojo::URL->to_string does not re-escape it on output. I can't see the reason for that call to url_unescape in parse(). The query part and fragment have the same syntax rules in all 3 specs, so I would expect them to get the same treatment as far as unescaping.

sri noted on IRC that this test failed if you remove the unescaping for URL fragments: https://github.com/kraih/mojo/blob/master/t/mojo/request.t#L2101

I think that test is using an invalid URL (contains unescaped percent character), so users relying on that behaviour would also be using invalid URLs.

I don't see any need for an object of some sort to manage fragments (as Mojo::Parameters may be used for query part). Fragments can be treated as opaque strings - there is no key=value convention for fragment as there is for query. Leave it up to users to construct a properly escaped URL for parsing, as Mojo::URL already assumes when string is passed to accessors. In this context, fragments are just strings that need to be properly escaped for inclusion in URLs. Except for percent signs, Mojo::URL already does this.

**Comment by kraih** [comment]
```
say Mojo::URL->new("/foo?bar=1%25+nacl#1%25+nacl")
# /foo?bar=1%25+nacl#1%+nacl
```
@ilainftw If this behavior is in fact not allowed by the specs, please open a new issue and report this as a bug, with references to the spec sections in question.

**Comment by dboehmer** [comment]
The *URL living standard* [says in section 4.1](https://url.spec.whatwg.org/#syntax-url-fragment)

> A URL-fragment string must be zero or more URL units. 

and [defines URL units](https://url.spec.whatwg.org/#url-units)

> The URL units are URL code points and percent-encoded bytes. 

A `%` is obviously not anything percent-encoded. Is it a URL code point? [The list of valid code points](https://url.spec.whatwg.org/#url-code-points) says it's not.

I hate to quote from this document which defines everything just be linking to another paragraph. That makes even reading difficult, not to mention quoting a particular point.

**Comment by dboehmer** [comment]
I'm going to sum this up in a new issue as @kraih requested.
