### ISSUE TITLE
Possible global destruction botch

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/mojo#1040]
* Mojolicious version: 7.20
* Perl version: 5.10.1
* Operating system: Ancient debian

    Use of uninitialized value $loop in hash element at /home/t0m/the-opan/perl5/lib/perl5/Mojo/UserAgent.pm line 194 during global destruction.
            (in cleanup) Can't call method "remove" on an undefined value at /home/t0m/the-opan/perl5/lib/perl5/Mojo/UserAgent.pm line 270 during global destruction.

Seems like it should notice and not try and do that - either by using a Devel::GlobalDestruction type approach or just a defined() check in DESTROY.

(a reliable repro is, as always for GD botches, kinda tricky, I saw this using 'opan carton' which hits the mojo daemon process with a SIGTERM to get rid of it when it's done)

**Comment by kraih** [comment]
Looks like this is only the case with Perl 5.10.x and 5.12.x. We don't care too much about those anymore, as long as they pass all tests that's good enough. http://mojolicious.org/perldoc/Mojolicious/Guides/FAQ#Which-versions-of-Perl-are-supported-by-Mojolicious

**Comment by haarg** [comment]
Something that might be useful for this is my module [Devel::GlobalPhase](https://metacpan.org/pod/Devel::GlobalPhase) that can emulate the `${^GLOBAL_PHASE}` variable on older perl versions.

It currently has some issues though.  Accurately detecting the END phase causes it to be rather slow and can potentially cause segfaults.  I'm considering making it slightly less accurate to fix those issues.  The issue is in detecting END vs RUN.  The DESTRUCT phase is always accurately detected.

**Comment by kraih** [comment]
I think most of us are indifferent on this, and `use Devel::GlobalPhase -var;` is a reasonable enough workaround for those that get annoyed by the warnings. So we'll leave it at that for now.
