### ISSUE TITLE
app->max_request_size($limit) is not behaving well for larg-ish uploaded files

### ISSUE THREAD

**Issue by akarelas-pt** [kraih/mojo#1164]
* Mojolicious version: 7.58
* Perl version: 5.26.0
* Operating system: Linux Fedora 25

### Steps to reproduce the behavior
I run this Mojolicious::Lite app with `morbo myapp.pl` on the same machine as my browser. I open the website with either Firefox (latest version) or Chromium, directly on port 3000, not through nginx or any reverse proxy or remote network connection. I upload a 100MB using the site's form, and I get an error screen on my browser.

The file myapp.pl is here: https://gist.github.com/akarelas-pt/892ba328a43ab0b14128ca82459279b5

### Expected behavior
My browser should show a JSON object with ```{title: "hi there", exceeded: 1}```

### Actual behavior
I got a browser error screen. I don't get this browser error screen when I set max_request_size to 200MB, though, which makes me think that it's the mojo framework's fault. Also, I don't get this error when the uploaded file is only 100kB and max_request_size is 10kB.

**Comment by kraih** [comment]
I can confirm the problem. My guess is that it might be the result of an accidental security feature that closes the connection early.

**Comment by kraih** [comment]
This doesn't actually look like a bug to me. What happens is that Mojolicious renders a response as soon as it recognizes that the upload is too big and sends the full response before closing the connection. Chrome receives the response, but is not done uploading the bug file, so the connection gets closed before it is done and considers this an error. So it displays an error message instead of the response. Not sure there is much we could do to handle this problem better.
