### ISSUE TITLE
mojolicious can not  parse the json request

### ISSUE THREAD

**Issue by haryzhou** [kraih/mojo#522]
the request is  initiatied by jquery ajax 

```
$.ajax({
    type: "POST",
    contentType: "application/json; charset=utf-8",
    url: "/json",
    anysc: false,
    data: { propertyList: 'productPropertyTemplate', a : [ 1, 2, 3, 4] },
    dataType: "json",
    success: function (result) { alert(result.d) },
    error: function (XMLHttpRequest, textStatus, errorThrown) {
        alert(errorThrown + ':' + textStatus);
    }
});
```

you can see the data sent from firefox to my mojolicious server  '/json'

![4c29803e-b7bc-487f-a9c3-d7d211603f8c](https://f.cloud.github.com/assets/1912208/937205/dae96c6c-00d2-11e3-91d4-6e613d471d82.png)

my mojolicious server action is as follow:

post '/json' => sub {
    my $self = shift;
    my $json = $self->req->body;
    warn "got json[$json]";
    $json = url_unescape($json);
    warn "got json[$json]";
    $json = decode_json($json);
    Data::Dump->dump($json);
    $self->render(text => $json);
};

the error message is as follow:
[Fri Aug  9 17:00:31 2013] [debug] POST "/json".
[Fri Aug  9 17:00:31 2013] [debug] Routing to a callback.
got json[propertyList=productPropertyTemplate&a%5B%5D=1&a%5B%5D=2&a%5B%5D=3&a%5B%5D=4] at json line 22.
got json[propertyList=productPropertyTemplate&a[]=1&a[]=2&a[]=3&a[]=4] at json line 24.
[Fri Aug  9 17:00:31 2013] [error] malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "propertyList=product...") at json line 25.

**Comment by dancingfrog** [comment]
Thank you, @Tekki 

From https://github.com/kraih/mojo/wiki/Request-data
> It's also worth pointing out that you can decode a hashref of POSTed JSON data with:
>
>   ` my $data = $c->req->json;`

... "worth pointing out" is a bit of an understatement, maybe the reason that the top google results for "Mojolicious parse JSON body" are people complaining about not being able to do it...

**Comment by jberger** [comment]
@dancingfrog I'm not sure why you are worried, one of those posts was someone passing invalid JSON (single quotes rather than double) and this one they OP is clearly sending urlencoded data, not JSON. I don't see any purpose of dredging up this old thread for snark though.

**Comment by dancingfrog** [comment]
Sorry if my wording is coming across snark, I don't intend to be. Yeah I'm not really adding anything to this conversation other than echoing the sentiment that, as motivated as I am to use Mojolicious in projects, after scanning the documentation on both Mojolicio.us and CPAN, I still have to resort to googling for very basic functionality, like how to parse json from the POST body, because such functionality is not given much attention in the documentation. I should be doing this project in Express if only because of the ease of finding what I'm looking for in terms of understanding, however I *really like* the pieces of Mojolicious that I do understand and I want to support it's development, so I will spend 25% longer coding a module in Perl rather than Node. I'm only disappointed that  despite my interest and investment, over the years this process has not gotten any easier. Maybe its just a Perl thing...

@jberger, I did not "dredge" up this thread, nor would I have even read it, if it were not the top most result for the question I was asking (and consequently actually contains the answer I was looking for):
![mojo_parse](https://cloud.githubusercontent.com/assets/12377567/16509511/84544212-3f0b-11e6-803f-17f122d82696.png)

**Comment by kraih** [comment]
> Maybe its just a Perl thing...

Go pick a fight somewhere else, i'm locking this issue.
