### ISSUE TITLE
Not preserved optional field values sequence

### ISSUE THREAD

**Issue by kak-tus** [kraih/mojo#826]
Latest master don't preserve values sequence for optional field vith multiple values.

In input we have 
```
foo => [ '', 'bar' ]
```

And in output we got only
```
foo => ['bar']
```

It's wrong. See
http://stackoverflow.com/questions/4027635/do-browsers-preserve-order-of-inputs-with-same-name-on-get-post

Sometimes values order is very important, even if some of them are empty.

If you see my MR - there input and output of optional fields are identical by this reason.

**Comment by kraih** [comment]
I've reverted my previous commits regarding #824 and #825, since clearly there is more to be discussed. https://github.com/kraih/mojo/commit/97f6f441530791709d96deb160feaec67ca1d37c And considering the number of design problems popping up, it might be worth reconsidering if changes are necessary at all. Multiple optional values are a fringe use case, and already not supported by the tag helpers.

**Comment by kraih** [comment]
Closing this issue since it does not apply anymore. We'll need a new one to discuss handling of multiple optional values as a new feature (i do not see it as a bugfix anymore).
