### ISSUE TITLE
Mojo::DOM->val returns on for non-checkbox/radio buttons fields

### ISSUE THREAD

**Issue by ksmadsen** [kraih/mojo#926]
With Mojolicious 6.50, Mojo::DOM now returns 'on' if a text-input field contains an empty value:

```perl
use Mojo::DOM;
my $dom = Mojo::DOM->new("<input type=\"text\" value>");
say $dom->at("input")->val();
```

The above will output "on", instead of the expected empty line.

**Comment by jhthorsen** [comment]
@ksmadsen: This is not an accident.

* https://github.com/kraih/mojo/commit/127b20dc4d9b6367b946097b40bde1f18a68d8ff
* https://github.com/kraih/mojo/pull/916
* https://www.w3.org/TR/html5/forms.html#dom-input-value-default-on

**Comment by mbudde** [comment]
@jhthorsen: The bug here is that "on" is returned for ``input`` elements that are **not** checkboxes or radio buttons. The "default/on" attribute mode is only specified for the ``value`` attribute on checkbox/radio elements (see https://www.w3.org/TR/html5/forms.html#input-type-attr-summary). I believe the bug was introduced in a6b7d85 where ``$self->{type} // '' eq $_`` should have been ``($self->{type} // '') eq $_``.

**Comment by kraih** [comment]
Thanks, fixed.

**Comment by jhthorsen** [comment]
@mbudde: Ah, I'm very sorry! Thanks for clearing that up.
